-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyAWrinn3SkdAvKKt
zalWOTA8DcUU72lvqRKs1mzudNSgCgYIKoZIzj0DAQehRANCAATafPUFqSx9lppe
TsfLlcpBJXnT+NglaUn8qMhA3UOP8IuQPjExvKxe+A7IQlmY8mff/5N9/ani0d24
HOk95Wg+
-----END PRIVATE KEY-----