workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: ad_hoc  # 或 app_store
        bundle_identifier: com.example.sleptWell  # 你的 Bundle ID
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files $(BUNDLE_ID) --type IOS_APP_ADHOC --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build iOS
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - 2066575268@qq.com  # 你的邮箱
        notify:
          success: true
          failure: true

  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com  # 替换为你的邮箱
